// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNAlVgymn7QeXdvkTjBNdr2fpZ3zSZG2g',
    appId: '1:663487277505:web:5ecdab534bae0f276b6740',
    messagingSenderId: '663487277505',
    projectId: 'temjeito-tcc',
    authDomain: 'temjeito-tcc.firebaseapp.com',
    storageBucket: 'temjeito-tcc.firebasestorage.app',
    measurementId: 'G-4NJDHKBM4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSyVzeZidVzqSxkBqeQs034SX67Uv3DQ',
    appId: '1:663487277505:android:0dc994797a3665496b6740',
    messagingSenderId: '663487277505',
    projectId: 'temjeito-tcc',
    storageBucket: 'temjeito-tcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkjXJuObZp9Hs43iTbosYBqzRG8stkkkA',
    appId: '1:663487277505:ios:543467732b63009c6b6740',
    messagingSenderId: '663487277505',
    projectId: 'temjeito-tcc',
    storageBucket: 'temjeito-tcc.firebasestorage.app',
    iosBundleId: 'com.example.temjeito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkjXJuObZp9Hs43iTbosYBqzRG8stkkkA',
    appId: '1:663487277505:ios:543467732b63009c6b6740',
    messagingSenderId: '663487277505',
    projectId: 'temjeito-tcc',
    storageBucket: 'temjeito-tcc.firebasestorage.app',
    iosBundleId: 'com.example.temjeito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNAlVgymn7QeXdvkTjBNdr2fpZ3zSZG2g',
    appId: '1:663487277505:web:a0eff914aad1e2ab6b6740',
    messagingSenderId: '663487277505',
    projectId: 'temjeito-tcc',
    authDomain: 'temjeito-tcc.firebaseapp.com',
    storageBucket: 'temjeito-tcc.firebasestorage.app',
    measurementId: 'G-E8Z37KLY3L',
  );

}